version: "3.8"

services:
  jupyterlab:
    build:
      context: ..
      dockerfile: human_eval/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    command: jupyter lab --ip=0.0.0.0 --allow-root --port=8888 --no-browser
